sudo: required
services:
- docker
language: node_js
node_js:
- '8'
- '6'
before_install:
- npm run docker-up
script:
- npm run test-lint
- npm run build
- npm run test-unit
- npm run test-validation
deploy:
  on:
    node: '8'
  provider: heroku
  api_key:
    secure: toto
